In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("train.csv")

In [3]:
df.head()

label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0      1       0       0       0       0       0       0       0       0   
1      0       0       0       0       0       0       0       0       0   
2      1       0       0       0       0       0       0       0       0   
3      4       0       0       0       0       0       0       0       0   
4      0       0       0       0       0       0       0       0       0   

   pixel8  ...  pixel774  pixel775  pixel776  pixel777  pixel778  pixel779  \
0       0  ...         0         0         0         0         0         0   
1       0  ...         0         0         0         0         0         0   
2       0  ...         0         0         0         0         0         0   
3       0  ...         0         0         0         0         0         0   
4       0  ...         0         0         0         0         0         0   

   pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0  
1         0         0         0         0  
2         0         0         0         0  
3         0         0         0         0  
4         0         0         0         0  

[5 rows x 785 columns]

In [4]:
df.columns

Index(['label', 'pixel0', 'pixel1', 'pixel2', 'pixel3', 'pixel4', 'pixel5',
       'pixel6', 'pixel7', 'pixel8',
       ...
       'pixel774', 'pixel775', 'pixel776', 'pixel777', 'pixel778', 'pixel779',
       'pixel780', 'pixel781', 'pixel782', 'pixel783'],
      dtype='object', length=785)

In [5]:
df.isnull().sum()

label       0
pixel0      0
pixel1      0
pixel2      0
pixel3      0
           ..
pixel779    0
pixel780    0
pixel781    0
pixel782    0
pixel783    0
Length: 785, dtype: int64

In [6]:
df_target = df[['label']]

In [9]:
df_target.sample(4)

label
16459      7
27948      6
1134       8
16402      4

In [10]:
df = df.drop(['label'], axis = 1)

In [11]:
df.head(4)

pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
0       0       0       0       0       0       0       0       0       0   
1       0       0       0       0       0       0       0       0       0   
2       0       0       0       0       0       0       0       0       0   
3       0       0       0       0       0       0       0       0       0   

   pixel9  ...  pixel774  pixel775  pixel776  pixel777  pixel778  pixel779  \
0       0  ...         0         0         0         0         0         0   
1       0  ...         0         0         0         0         0         0   
2       0  ...         0         0         0         0         0         0   
3       0  ...         0         0         0         0         0         0   

   pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0  
1         0         0         0         0  
2         0         0         0         0  
3         0         0         0         0  

[4 rows x 784 columns]

In [18]:
from sklearn import preprocessing

In [16]:
y = df_target
x = df

In [19]:
min_max_scaler = preprocessing.MinMaxScaler()

In [20]:
x = min_max_scaler.fit_transform(x)

In [21]:
from sklearn.model_selection import train_test_split

In [22]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.20)

In [23]:
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn import svm

In [24]:
clf = svm.SVC()

In [25]:
clf.fit(x_train, y_train)

/home/temporary/.local/lib/python3.6/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


SVC()

In [26]:
y_pred = clf.predict(x_test)

In [27]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report, confusion_matrix

In [28]:
accuracy_score(y_test, y_pred)

0.9761904761904762

In [29]:
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[809   0   0   0   1   0   2   0   1   1]
 [  0 948   4   1   4   1   0   1   1   0]
 [  2   1 797   3   3   0   2   3   4   1]
 [  0   1   5 849   1  12   0   6   8   3]
 [  2   0   2   0 769   1   0   2   1  12]
 [  3   0   0   8   3 737   4   0   2   1]
 [  4   0   1   0   0   5 824   0   3   0]
 [  2   4   4   0   3   0   0 853   0  12]
 [  1   1   1   5   1   2   1   1 801   1]
 [  1   1   1   5  11   0   0   9   7 813]]
              precision    recall  f1-score   support

           0       0.98      0.99      0.99       814
           1       0.99      0.99      0.99       960
           2       0.98      0.98      0.98       816
           3       0.97      0.96      0.97       885
           4       0.97      0.97      0.97       789
           5       0.97      0.97      0.97       758
           6       0.99      0.98      0.99       837
           7       0.97      0.97      0.97       878
           8       0.97      0.98      0.98       815
           9       0.96     

In [30]:
np.unique(df_target['label'], return_counts = True)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([4132, 4684, 4177, 4351, 4072, 3795, 4137, 4401, 4063, 4188]))

In [31]:
from sklearn.metrics import classification_report

In [32]:
y_true = y_test
y_pred = y_pred
target_names = ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [34]:
print(classification_report(y_true, y_pred, target_names=target_names))

              precision    recall  f1-score   support

           0       0.98      0.99      0.99       814
           1       0.99      0.99      0.99       960
           2       0.98      0.98      0.98       816
           3       0.97      0.96      0.97       885
           4       0.97      0.97      0.97       789
           5       0.97      0.97      0.97       758
           6       0.99      0.98      0.99       837
           7       0.97      0.97      0.97       878
           8       0.97      0.98      0.98       815
           9       0.96      0.96      0.96       848

    accuracy                           0.98      8400
   macro avg       0.98      0.98      0.98      8400
weighted avg       0.98      0.98      0.98      8400



In [35]:
from sklearn.metrics import balanced_accuracy_score


In [36]:
balanced_accuracy_score(y_true, y_pred)

0.9761885222274105

In [37]:
from sklearn.metrics import cohen_kappa_score

In [38]:
cohen_kappa_score(y_true, y_pred)

0.9735337283802462